### ISSUE TITLE
Allow weak passwords

### ISSUE THREAD

**Issue by jnewbery** [joule-labs/joule-extension#102]
What can I say, I'm reckless.

Seriously though, for testing (and demoing when holding a mic in one hand!) it'd be nice to have a short password.

I can understand why you wouldn't want to allow this though. Perhaps as a hidden option?

**Comment by wbobeirne** [comment]
Totally reasonable ask. I could change it to be a double-confirm with a message that explains the importance of good security and all that jazz. Though this might be more of a symptom of #96 than a big problem. If you only had to enter it once per session then it wouldn't be so painful.
