### ISSUE TITLE
Option to connect to Bluewallet

### ISSUE THREAD

**Issue by bitcoinuser** [joule-labs/joule-extension#128]
Hi,

Bluewallet (https://bluewallet.io/) is a wallet that support lightning. It's a hosted wallet. 
I think Joule could have an option to connect to Bluewallet (https://medium.com/bluewallet/bluewallet-brings-zero-configuration-lightning-payments-to-ios-and-android-30137a69f071)

Thanks.

**Comment by wbobeirne** [comment]
I don't see any readily-available API for accessing the user's account. It looks like they've got a custom solution called LndHub for allowing many users to use a single LND node, but the docs are pretty sparse.

**Comment by Overtorment** [comment]
Oh hey!
API specs are here https://github.com/BlueWallet/LndHub/blob/master/doc/Send-requirements.md
And the reference client implementation is here: https://github.com/BlueWallet/BlueWallet/blob/master/class/lightning-custodian-wallet.js
Complete acceptance tests suite is here https://github.com/BlueWallet/BlueWallet/blob/master/LightningCustodianWallet.test.js

API specs need a little cleanup, but I think the client can be used right away (its js, and we use it in ReactNative).
LndHub is just a simple wrapper around LND, can be easily hosted on Heroku. You got it right, it is for a single LND node to serve several users.

**Comment by wbobeirne** [comment]
Awesome, thanks for the details. So for BlueWallet users, you have a default hosted LndHub instance? Is there a way a user can give me credentials for that?

**Comment by Overtorment** [comment]
Yes, default hosted instance is lndhub.herokuapp.com (you can see it in
sources). User can easily export his credentials from Bluewallet (open
wallet->options->export).

**Comment by lylepratt** [comment]
@wbobeirne Telegram: https://t.me/bluewallet

**Comment by Overtorment** [comment]
@wbobeirne hit me up on https://t.me/overtorment
