### ISSUE TITLE
"unable to find node" error when pasting invoice

### ISSUE THREAD

**Issue by VanStam** [joule-labs/joule-extension#174]
### Description of the Issue

I get the error "unable to find node" when I paste the invoice in the payment request box. My node is well connected and I have properly funded channels. I tried the same invoice with the Zap Desktop wallet and it worked
I have sent and received several payments with the Joule extension without any problems so far. 

*Browser & version*: Chrome 72.0.3626.109 
*Operating system*: Linux
*Node software & version*: lnd 0.5.1-beta

**Comment by wbobeirne** [comment]
Hey, thanks for the heads up. Would you mind right clicking on the extension, doing "Inspect popup", going over to the "Network" tab in the inspector, and pasting the response that your node gave when you paste it in? It should be a request to a URL like `.../graph/routes/...`

**Comment by VanStam** [comment]
Hi,
I did as you said. The response says:
{"error":"target not found","code":2}

**Comment by wbobeirne** [comment]
Hmm, I'm unable to find where in lnd that error throws with that specific message. Are Zap and Joule hooked up to the same node?

**Comment by wbobeirne** [comment]
Also had another thought, is it an any-amount invoice? Can you paste the invoice here so I can decode it and see what values it has? For any amount invoices, I try to do a graph route for 1 satoshi, which may fail if some nodes along the way have a minimum  spend amount.

**Comment by VanStam** [comment]
yes they 're on the same node. It 's for 180000 sats. 
Noob question: Is it ok privacy-wise to post a ln invoice here?

**Comment by wbobeirne** [comment]
Gotcha, I'm kind of stumped here. Looks like an issue with lnd's graph routes endpoint not working the same as its payment endpoint. It's a little out of my hands at that point. Sorry I can't give a more satisfying answer.

As for privacy, it only reveals information about _their_ node, not yours. The only reason you'd not want to post an invoice would be if you didn't want people aware of what you were purchasing (Which they could only tell if they knew what the node was selling / it was in the description) or you didn't want the invoice generator to know anything about you (they could corroborate this github post with the paid invoice to know who you are.)

**Comment by VanStam** [comment]
I tried a few more invoices from yalls, bluewallet. Joule gives that error only with invoices from a specific node, a Kumaigorodskiy's Lightning mobile wallet (zap finds it though). Hope it helps somehow. No worries, Joule is already quite amazing, keep on.  
Thanks for the detailed answer

**Comment by andronoob** [comment]
I'm trying to send from my LND node to [BLW](https://github.com/btcontract/lnwallet). Joule complained "unable to find node" when pasting invoice, but lncli payinvoice worked.

**Comment by wbobeirne** [comment]
Interesting, it's possible the CLI differs from the REST endpoint somehow. I'll have to dig into LND's code to understand where that might be.

**Comment by andronoob** [comment]
I'm still very confused. Sometimes payinvoice complains "unable to find a path to destination", too, while the outbound capacity of the channel seems to be sufficient.

**Comment by andronoob** [comment]
Also, BLW won't announce the channel. It embeds a routing hint into the invoice. Maybe the problem is related to this?

**Comment by andronoob** [comment]
LND itself seemed to have some problem, too, if I recalled correctly. I was trying to pay yalls with merely 150 sats, but LND still complained it cannot find a route. Now this problem has disappeared. 🤷‍♂️

**Comment by wbobeirne** [comment]
> Also, BLW won't announce the channel. It embeds a routing hint into the invoice. Maybe the problem is related to this?

Ah, THAT'S the problem. I try to query for a route first. I'll have to rethink this behavior then, I didn't anticipate this case.

**Comment by wbobeirne** [comment]
This was smoothed over with #220. QueryRoutes still fails, but Joule will let you make the payment.
