### ISSUE TITLE
makeInvoice with 0 doesn't work

### ISSUE THREAD

**Issue by torkelrogstad** [joule-labs/joule-extension#195]
### Description of the Issue

Requesting an invoice with any of the numerical options set to `0` doesn't work

### Steps to Reproduce

```typescript
makeInvoice({
  amount: 0
})
```

and observe that the option isn't being respected. This also applies to the rest of the numerical options. 

### Description of Your Setup

*Browser & version*: Firefox 66.0.2
*Operating system*: Ubuntu 18.10
*Node software & version*: LND 0.5.2

**Comment by wbobeirne** [comment]
Looks like this is a falsy check issue, seeing as `amount: "0"` does work. Thanks for the heads up.
