### ISSUE TITLE
"Balances" screen shows error

### ISSUE THREAD

**Issue by torkelrogstad** [joule-labs/joule-extension#196]
### Description of the Issue

The "balances" screen does not work, gives an error message. 

### Steps to Reproduce

Open the drop down menu in the right hand corner, and click on "balances".

### Description of Your Setup

*Browser & version*: Firefox 66
*Operating system*: Ubuntu 18.10
*Node software & version*: LND 0.5.2

### Console Logs / Screenshots

From console:

```
API error calling GET /v1/utxos Error: "Not Found"
    t index.js:8
    request index.js:8
    s index.js:8
    s index.js:8
    s index.js:8
    o schedule.production.min.js:10
    A schedule.production.min.js:10
    c schedule.production.min.js:10
```

Screenshot: 
![image](https://user-images.githubusercontent.com/16610775/55316037-d8624c80-546d-11e9-974c-9688a652567a.png)

**Comment by wbobeirne** [comment]
This is very strange, the UTXOs endpoint is documented here: https://api.lightning.community/rest/index.html#v1-utxos. Is there anything abnormal about your node, or the current state of your UTXOs? If you run `lncli listunspent --min_confs=0` do you have any issues?

As an aside, we should make this error look much nicer, and be failure-resistant for individual calls and just use empty arrays instead.

**Comment by torkelrogstad** [comment]
It is very strange indeed, it appears the UTXO endpoint is simply not there. Included the output of `getinfo`, with identifying information removed

```
$ lncli --version
lncli version 0.5.2-beta commit=v0.5.2-beta

$ lncli getinfo
{
    "block_height": 570310,
    "block_hash": "00000000000000000010ccd9b0f8b70421294c880f54a03e789a21587d42fcf8",
    "synced_to_chain": true,
    "testnet": false,
    "chains": [
        "bitcoin"
    ],
    "best_header_timestamp": "1554465427",
    "version": "0.5.2-beta commit=v0.5.2-beta",
}


$ lncli listunspent 
No help topic for 'listunspent'

$ lncli listunspent --min_confs=0
No help topic for 'listunspent'
```
IIRC I only have one small UTXO on my LND node, rest is in channels. Is there any other way for me to inspect that?

**Comment by wbobeirne** [comment]
I've poked around at the LND code, and can't find anywhere that would make the `/v1/utxos` endpoint / `listunspent` command conditional. Since I can't replicate, I'm just going to leave this as is. Very strange indeed, might be worth asking around in the LND slack if this persists after upgrading to 0.6.0.
