### ISSUE TITLE
Connection problem URL formats with double-slash

### ISSUE THREAD

**Issue by wbobeirne** [joule-labs/joule-extension#198]
### Description of the Issue

Got a message about this:

> just an FYI, when I click on the connection problem link fixer thing in the 0.5.0 version it puts in a double slash... `https://localhost:3000//v1/getinfo`

Requires a little further investigation.

### Steps to Reproduce

?

**Comment by githorray** [comment]
This is my REST API URL in the settings if that helps...

![image](https://user-images.githubusercontent.com/39980780/55862811-ce49f780-5bab-11e9-8228-3e8c7a6b9856.png)

**Comment by githorray** [comment]
Ok I can reproduce this issue now.

During initial setup I can use either https://localhost:3000 or https://localhost:3000/ and setup completes. Notice the only difference in the two URL's is the trailing slash.

Using the URL with the trailing slash will cause the issue with the double slash when trying to repair the connection.

The link is built here:
https://github.com/wbobeirne/joule-extension/blob/e1e3bfe9ff54cd9be1526cdea1adbc5964f31e8e/src/app/components/ConnectionFailureModal/index.tsx#L24
