### ISSUE TITLE
Show banner when synced_to_chain is false

### ISSUE THREAD

**Issue by wbobeirne** [joule-labs/joule-extension#199]
### Description of the Feature or Idea

Noticed this while watching someone upgrade today, if your getInfo response has `synced_to_chain: false`, we should display a banner warning you that you are syncing and may be missing funds temporarily. This can avoid a lot of user confusion.

**Comment by callmekurisu** [comment]
Was thinking about displaying an icon similar to the clock for the pending balances. Maybe a red exclamation mark with warning message in a popover? Should have this done this weekend

**Comment by wbobeirne** [comment]
Hope you don't mind, I'm in small issue squash mode today in the hopes of getting a 0.5.1 out soon so I knocked this one out. Thanks for volunteering though!
