### ISSUE TITLE
Opening channel TX not opening in block explorer on testnet

### ISSUE THREAD

**Issue by torkelrogstad** [joule-labs/joule-extension#201]
### Description of the Issue

Opening a channel funding TX in the Blockstream block explorer fails to account for testnet.

### Steps to Reproduce

1. Open up a channel on testnet
2. Click on Joule 
3. Click on the pending channel
4. Click on the `Funding Tx link`
5. See error

### Description of Your Setup

*Browser & version*: Chromium 73.0.3683.75
*Operating system*: Ubuntu 18.10
*Node software & version*: `0.6.0-beta commit=v0.6-beta-rc3`

**Comment by torkelrogstad** [comment]
This also applies when creating a channel through Joule, I just found out.

**Comment by wbobeirne** [comment]
Thanks for the find, definitely looks like there's no handling here. We'll just need to put something together similar to the way we display text differently for various chains and networks.
