### ISSUE TITLE
Transactions tab crashes for some nodes

### ISSUE THREAD

**Issue by wbobeirne** [joule-labs/joule-extension#206]
### Description of the Issue

Getting a report of the transactions page not loading, with an error of "Cannot read property length of undefined". Narrowed it down to the following but of code:

https://github.com/joule-labs/joule-extension/blob/develop/src/app/modules/account/sagas.ts#L68-L70

Looks like sometimes payments come back with an undefined (or empty, due to the rest rpc bug) path array, so we'll just need to add it to the RPC call default properties:

https://github.com/joule-labs/joule-extension/blob/develop/src/app/lib/lnd-http/index.ts#L183

### Steps to Reproduce

Unknown, but can be fixed without reproducing

**Comment by githorray** [comment]
Confirmed working on my old crusty node. Thank you.
