### ISSUE TITLE
Open Channel 

### ISSUE THREAD

**Issue by lrgeoemtry** [joule-labs/joule-extension#212]
Hi there
We’re a merchant using the c-lighitng and btcpay server

Some of your users are experiencing a lack of inbound capacity. 

Would you mind opening a channel with us? 
https://1ml.com/node/026f9c01e266863c0539ef98bfe4ecd585e6a7ee13ec42b4e09736a5a6f7152ee7 

Thanks

Futjrn 
Lead Dev.

**Comment by wbobeirne** [comment]
Hey there, Joule is a non custodial application, so there is no large hub node to open channels from. I suggest you look into a channel opening service, such as the Lightning Power User's, or Bitrefill's Thor service.

https://lightningpowerusers.com/home/
https://www.bitrefill.com/thor-lightning-network-channels/?hl=en
