### ISSUE TITLE
makeInvoice contradicts itself

### ISSUE THREAD

**Issue by Technifocal** [joule-labs/joule-extension#213]
### Description of the Issue

makeInvoice() contradicts itself, it states the value is both in seconds and hours

### Steps to Reproduce

1. makeInvoice()
2. 
![Contradiction](https://user-images.githubusercontent.com/20205745/58438940-7c145580-80c9-11e9-9340-8579496ca577.png)

### Console Logs / Screenshots

See above, [here](https://github.com/joule-labs/joule-extension/blob/5972c6c82cd2dc7770706eea11a059d7bcd7071e/src/app/prompts/invoice.tsx#L164) is the line that needs changing (I believe).

**Comment by bolatovumar** [comment]
This seems to have been fixed in the `develop` branch here: https://github.com/joule-labs/joule-extension/blob/develop/src/app/prompts/invoice.tsx#L183

**Comment by wbobeirne** [comment]
Right you are. Should have a new release out soon with that in it.
