### ISSUE TITLE
Errors disappear too quickly

### ISSUE THREAD

**Issue by dmidnight** [joule-labs/joule-extension#227]
### Description of the Issue

When an error is displayed, it disappears too quickly to actually read it.

### Steps to Reproduce

Tried to pay an invoice

### Description of Your Setup

*Browser & version*: Brave Version 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
*Operating system*: Ubuntu 18.04
*Node software & version*: LND 0.7.1-beta, Joule 0.5.1
### Console Logs / Screenshots

[Please provide these if you can!]

I do not see any console.log output. Is there a log to view?

**Comment by wbobeirne** [comment]
The production build has a lot of logging stripped so you probably can't dive into the details, sorry. You're absolutely right though, errors with paying invoices should persist here, not dismiss after a few seconds.
