### ISSUE TITLE
Cannot use lnd server with Brave Browser

### ISSUE THREAD

**Issue by Javihache** [joule-labs/joule-extension#240]
I have set up and lnd node and a bitcoind node with docker-compose. I got REST on port 8082. In lnd.conf I got 

tlsextraip=myipaddress
tlsextraip=0.0.0.0

I regenerated the tls certificates, but everytime I try to connect I get the message below.
```
Failed to connect to node
Request failed with the message "Failed to fetch"

If you're sure you've setup your node correctly, try clicking this link and making sure it loads correctly. If there are SSL errors, click "advanced" and proceed to accept the certificate.
```

If I try to access http://ipaddress:8082 over the browser I get 
 `Client sent an HTTP request to an HTTPS server.`

If I open https://ipaddress:8082 over the browser, Brave doesn't allow me to create an exception like other browsers do. 

In Firefox it works fine, since Firefox allows to create an exception.

**Comment by wbobeirne** [comment]
That's unfortunate, looks like you'll have to add the certificate to your computer's certificate keychain. Go to `brave://settings` and search for the "Manage certificates" setting. Click that, and it'll open your operating system's cert manager. You'll then need to add the LND certificate in here.

It's different for each operating system, so you may need to look up how to do this. On the bright side, once you do this here it'll fix it for every browser on your machine!
