### ISSUE TITLE
Question : how my webapp connect to Joule

### ISSUE THREAD

**Issue by vinhyenvodoi98** [joule-labs/joule-extension#241]
when open webapp it show this popup 

![image](https://user-images.githubusercontent.com/33363513/70224194-7043d300-177f-11ea-9c93-b6e4ddbec3d2.png)

how do they do it ?
Could u give me an example code ? 
Thanks!!!

**Comment by wbobeirne** [comment]
Hey @vinhyenvodoi98, you can check out https://webln.dev/ for more explanations and guides on how to hook up your app. If you have any issues with the implementation there, you can open issues on https://github.com/joule-labs/webln/issues
