### ISSUE TITLE
Idea: be able to link mobile non custodial wallets with Joule extension

### ISSUE THREAD

**Issue by bitcoinuser** [joule-labs/joule-extension#242]
Something like this will be amazing:

https://github.com/ACINQ/phoenix/issues/10

**Comment by wbobeirne** [comment]
Definitely like the idea but as noted in that linked issue, that's not something Phoenix or, to my knowledge, any other mobile lightning wallet supports.

If you're aware of any that have that capability feel free to open an issue for a particular wallet, but I'm going to close this issue as it's nothing that Joule can integrate with at the moment.
