### ISSUE TITLE
Automated Channel Management via Loop

### ISSUE THREAD

**Issue by reemuru** [joule-labs/joule-extension#249]
### Automated Channel Management

In order to form a more perfect union... j/k (^_^)
Let's add experimental feature for selecting a channel to handle automated looping in/out.
Start with default terms and get more advanced in future releases.
Place a button on the channel info
If on will enable... C.H.A.R.M!
In order to work the the primary wallet will have to keep at least 50% of the selected channel's capacity, or else it will automatically deactivate.

![image](https://user-images.githubusercontent.com/13033037/79676448-65c92980-81b4-11ea-8574-3cf3c8ccc149.png)

![image](https://user-images.githubusercontent.com/13033037/79917171-fa6f9980-83f7-11ea-87eb-a2de4d874d53.png)

Edit: typo (T_T)

**Comment by wbobeirne** [comment]
CHARM was an awesome concept, but I'm going to try to refocus Joule to do a very limited set of things very well, rather than have it try to do everything. I hope you eventually get this into a standalone CLI tool / daemon / web interface though!
