### ISSUE TITLE
Please use another bitcoin fees API provider

### ISSUE THREAD

**Issue by bretton** [joule-labs/joule-extension#275]
### Description of the Issue

`https://bitcoinfees.earn.com/api/v1/fees/recommended` is serving inaccurate & old data when calculating fees

### Steps to Reproduce

I did a search for `https://bitcoinfees.earn.com/api/v1/fees/recommended` and am alerting projects using this API to inaccurate & old data.

https://github.com/joule-labs/joule-extension/blob/1ba2050ef0dcfacdd6bfedf291acaff39d1baa8a/src/app/lib/earn.ts

### Description of Your Setup

n/a

### Console Logs / Screenshots

Suggested: use an up-to-date API with accurate data such as `https://mempool.space/api/v1/fees/recommended` or some alternative.

**Comment by wbobeirne** [comment]
Thanks for the heads up, yeah wow earn.com is giving some crazy recc's. I should probably make this configurable / throw it behind my own endpoint so that I can update it on the fly, but I'll use mempool.space for now. Thanks for the heads up.
